name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Temurin JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Install Mill
      run: |
        curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.7/0.11.7 -o mill
        chmod +x mill

    - name: Run tests
      run: ./mill cs.test
